package gorgonartisan

case class Recipe(
    ActionLabel: Option[String],
    Description: String,
    IconId: Int,
    Ingredients: List[ItemStack],
    InternalName: String,
    ItemMenuCategoryLevel: Option[Int],
    ItemMenuKeywordReq: Option[String],
    ItemMenuLabel: Option[String],
    Keywords: Option[List[String]],
    LoopParticle: Option[String],
    Name: String,
    Particle: Option[String],
    PrereqRecipe: Option[String],
    ProtoResultItems: Option[List[ItemStack]],
    ResetTimeInSeconds: Option[Int],
    ResultEffects: Option[List[String]],
    ResultItems: List[ItemStack],
    RewardSkill: String,
    RewardSkillXp: Int,
    RewardSkillXpDropOffLevel: Option[Int],
    RewardSkillXpDropOffPct: Option[Float],
    RewardSkillXpDropOffRate: Option[Int],
    RewardSkillXpFirstTime: Int,
    Skill: String,
    SkillLevelReq: Int,
    SharesResetTimerWith: Option[String],
    SortSkill: Option[String],
    UsageAnimation: Option[String],
    UsageAnimationEnd: Option[String],
    UsageDelay: Option[Float],
    UsageDelayMessage: Option[String],
) extends Content

case class RecipeProcessed(
    ActionLabel: Option[String],
    Description: String,
    IconId: Int,
    Ingredients: List[Processed[ItemStack]],
    InternalName: String,
    ItemMenuCategoryLevel: Option[Int],
    ItemMenuKeywordReq: Option[String],
    ItemMenuLabel: Option[String],
    Keywords: Option[List[String]],
    LoopParticle: Option[String],
    Name: String,
    Particle: Option[String],
    PrereqRecipe: Option[Content.Ref[Recipe]],
    ProtoResultItems: Option[List[Processed[ItemStack]]],
    ResetTimeInSeconds: Option[Int],
    ResultEffects: Option[List[String]], // refs tsysclientinfo?
    ResultItems: List[Processed[ItemStack]],
    RewardSkill: Info.Ref[Skill],
    RewardSkillXp: Int,
    RewardSkillXpDropOffLevel: Option[Int],
    RewardSkillXpDropOffPct: Option[Float],
    RewardSkillXpDropOffRate: Option[Int],
    RewardSkillXpFirstTime: Int,
    Skill: Info.Ref[Skill],
    SkillLevelReq: Int,
    SharesResetTimerWith: Option[Content.Ref[Recipe]],
    SortSkill: Option[Info.Ref[Skill]],
    UsageAnimation: Option[String],
    UsageAnimationEnd: Option[String],
    UsageDelay: Option[Float],
    UsageDelayMessage: Option[String],
) extends Processed[Recipe]
